Repository madisonrandle/whats-cookin, pull requests merged in 2020-03, with the labels that each got.

#3 Mvp
  .eslintrc
  .gitignore
  README.md
  src/css/reset.css
  src/css/styles.css
  src/images/activeFavorite.svg
  src/images/favoriteHover.svg
  src/images/inactiveFavorite.svg
  src/images/plus.svg
  src/images/plusHover.svg
  src/images/search.svg
  src/index.html
Labels: accessibility, enhancement

#5 Cookbook
  data/ingredients.js
  data/recipes.js
  data/users.js
  src/Cookbook.js
  test/cookbook-test.js
  test/pantry-test.js
  test/recipe-test.js
  test/user-test.js
Labels: bug

#8 Update dom
  src/css/styles.css
  src/index.html
  src/scripts.js
Labels: enhancement

#11 Pantry
  data/recipes.js
  src/Pantry.js
  test/cookbook-test.js
  test/pantry-test.js
Labels: enhancement
